// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRHH.Data;

#nullable disable

namespace RRHH.Migrations
{
    [DbContext(typeof(RRHHContext))]
    [Migration("20220213011849_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RRHH.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoAreaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoCargoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoTipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("NSS")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCuentaBanco")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SalarioOrdinario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EmpleadoAreaId");

                    b.HasIndex("EmpleadoCargoId");

                    b.HasIndex("EmpleadoEstadoId");

                    b.HasIndex("EmpleadoTipoId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("RRHH.Models.EmpleadoArea", b =>
                {
                    b.Property<int>("EmpleadoAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoAreaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoAreaId");

                    b.ToTable("EmpleadoArea");
                });

            modelBuilder.Entity("RRHH.Models.EmpleadoCargo", b =>
                {
                    b.Property<int>("EmpleadoCargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoCargoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoCargoId");

                    b.ToTable("EmpleadoCargo");
                });

            modelBuilder.Entity("RRHH.Models.EmpleadoEstado", b =>
                {
                    b.Property<int>("EmpleadoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoEstadoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoEstadoId");

                    b.ToTable("EmpleadoEstado");
                });

            modelBuilder.Entity("RRHH.Models.EmpleadoTipo", b =>
                {
                    b.Property<int>("EmpleadoTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoTipoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoTipoId");

                    b.ToTable("EmpleadoTipo");
                });

            modelBuilder.Entity("RRHH.Models.Empleado", b =>
                {
                    b.HasOne("RRHH.Models.EmpleadoArea", "EmpleadoArea")
                        .WithMany()
                        .HasForeignKey("EmpleadoAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.Models.EmpleadoCargo", "EmpleadoCargo")
                        .WithMany()
                        .HasForeignKey("EmpleadoCargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.Models.EmpleadoEstado", "EmpleadoEstado")
                        .WithMany()
                        .HasForeignKey("EmpleadoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.Models.EmpleadoTipo", "EmpleadoTipo")
                        .WithMany()
                        .HasForeignKey("EmpleadoTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoArea");

                    b.Navigation("EmpleadoCargo");

                    b.Navigation("EmpleadoEstado");

                    b.Navigation("EmpleadoTipo");
                });
#pragma warning restore 612, 618
        }
    }
}
